name: '1.1$(rev:.r)'

trigger:
- main
- features/*

pr:
- main

pool:
  vmImage: 'windows-2022'

variables:
  - name: 'extensionId'
    value: 'jessehouwing-vsts-msbuild-helper-task'
  - name: 'tfxVersion'
    value: '0.x'
  - name: 'nodeVersion'
    value: '16.x'
  - name: 'publisher'
    value: 'Jesse Houwing'

stages:
- stage: 'Build'
  displayName: 'Build'
  jobs:
  - job: 
    displayName: 'Build'
    steps:
    - task: NodeTool@0.213.0
      inputs:
        versionSpec: $(nodeVersion)
      displayName: 'Install Node.js'

    - task: replacetokens@4
      inputs:
        targetFiles: '**/task.json'
        encoding: 'utf-8'
        tokenPattern: 'default'
        writeBOM: false

    - script: |
        npm install
      workingDirectory: "./vsts-msbuild-helper/v0"
        
    - script: |
        npm run initdev
      workingDirectory: "./vsts-msbuild-helper/v0"
    
    - script: |
        npm run build
      workingDirectory: "./vsts-msbuild-helper/v0"

    - script: |
        npm install
      workingDirectory: "./vsts-msbuild-helper/v1"
        
    - script: |
        npm run initdev
      workingDirectory: "./vsts-msbuild-helper/v1"
    
    - script: |
        npm run build
      workingDirectory: "./vsts-msbuild-helper/v1"

    - task: TfxInstaller@4
      displayName: 'Use Node CLI for Azure DevOps'
      inputs:
        version: $(tfxVersion)
        checkLatest: true

    - task: PackageAzureDevOpsExtension@4
      displayName: 'Package Extension: $(Build.SourcesDirectory)'
      name: 'packageStep'
      inputs:
        rootFolder: '$(Build.SourcesDirectory)'
        outputPath: '$(Build.ArtifactStagingDirectory)\$(extensionId).vsix'
        publisherId: 'jessehouwing'
        extensionId: $(extensionId)
        extensionTag: '-build'
        extensionName: 'MsBuild Helper Tasks'
        extensionVersion: '$(Build.BuildNumber)'
        updateTasksVersion: true
        updateTasksVersionType: patch
        extensionVisibility: private

    - task: PublishPipelineArtifact@1.199.0
      displayName: 'Publish vsix'
      inputs:
        publishLocation: pipeline
        targetPath: '$(packageStep.Extension.OutputPath)'
        artifact: 'vsix'
      condition: succeededOrFailed()

- stage: PublishDev
  displayName: 'Publish privately'
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  dependsOn: 'Build'
  jobs:
    - deployment: 
      environment: Publisher JesseHouwing (privately)
      strategy: 
        runOnce:
         deploy:
          steps:
          - task: NodeTool@0
            inputs:
              versionSpec: $(nodeVersion)
            displayName: 'Install Node.js'

          - task: TfxInstaller@4
            displayName: 'Use Node CLI for Azure DevOps'
            inputs:
              version: $(tfxVersion)
              checkLatest: true

          - task: PublishAzureDevOpsExtension@4
            name: 'publishDev'
            inputs:
              connectTo: 'VsTeam'
              connectedServiceName: '$(publisher)'
              fileType: 'vsix'
              vsixFile: '$(Pipeline.Workspace)/vsix/$(extensionId).vsix'
              publisherId: 'jessehouwing'
              extensionId: '$(extensionId)'
              extensionTag: '-dev'
              updateTasksVersion: false
              updateTasksId: true
              extensionVisibility: 'privatepreview'
              shareWith: 'jessehouwing-dev'
              noWaitValidation: true
        
          - task: IsAzureDevOpsExtensionValid@4
            inputs:
              connectTo: 'VsTeam'
              connectedServiceName: $(publisher)
              method: 'vsix'
              vsixFile: '$(publishDev.Extension.OutputPath)'


          - task: PublishPipelineArtifact@1
            displayName: 'Publish vsix'
            inputs:
              publishLocation: pipeline
              targetPath: '$(publishDev.Extension.OutputPath)'
              artifact: 'dev'
            condition: succeededOrFailed()

- stage: PublishProd
  displayName: 'Publish publicly'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  dependsOn: 'PublishDev'
  jobs:
    - deployment: 
      environment: Publisher JesseHouwing (publicly)
      strategy: 
        runOnce:
         deploy:
          steps:

          - task: NodeTool@0
            inputs:
              versionSpec: $(nodeVersion)
            displayName: 'Install Node.js'
            
          - task: TfxInstaller@4
            displayName: 'Use Node CLI for Azure DevOps'
            inputs:
              version: $(tfxVersion)
              checkLatest: true

          - task: PublishAzureDevOpsExtension@4
            name: 'publishProd'
            inputs:
              connectTo: 'VsTeam'
              connectedServiceName: $(publisher)
              fileType: 'vsix'
              vsixFile: '$(Pipeline.Workspace)/vsix/$(extensionId).vsix'
              publisherId: 'jessehouwing'
              extensionId: '$(extensionId)'
              updateTasksVersion: false
              extensionVisibility: 'public'
              noWaitValidation: true
          
          - task: IsAzureDevOpsExtensionValid@4
            inputs:
              connectTo: 'VsTeam'
              connectedServiceName: $(publisher)
              method: 'vsix'
              vsixFile: '$(publishProd.Extension.OutputPath)'

          - task: PublishPipelineArtifact@1
            displayName: 'Publish vsix'
            inputs:
              publishLocation: pipeline
              targetPath: '$(publishProd.Extension.OutputPath)'
              artifact: 'prod'
            condition: succeededOrFailed()

          - task: GitHubRelease@1
            condition: false
            inputs:
              gitHubConnection: 'GitHub - jessehouwing'
              repositoryName: '$(Build.Repository.Name)'
              action: 'create'
              target: '$(Build.SourceVersion)'
              tagSource: 'userSpecifiedTag'
              tag: 'v$(Build.BuildNumber)'
              title: 'v$(Build.BuildNumber)'
              releaseNotesSource: 'inline'
              assets: |
                $(publishProd.Extension.OutputPath)*
                $(Pipeline.Workspace)/tasks/*
              changeLogCompareToRelease: 'lastFullRelease'
              changeLogType: 'issueBased'
              changeLogLabels: '[{ "state" : "closed" }]'
